server:
  port: 8073

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

spring:
  application:
    main:
      allow-bean-definition-overriding: true
    name: ShoppingCommandService
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gidcommand
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

feign:
  hystrix:
    enabled: true