server:
  port: 8073

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

spring:
  application:
    main:
      allow-bean-definition-overriding: true
    name: ShoppingCommandService
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
